# Generated by Django 3.1.5 on 2021-04-12 15:03

import core.shortcuts
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('type', models.CharField(choices=[('W', 'Word'), ('D', 'Dialogue'), ('S', 'Sentence')], default='W', max_length=1)),
                ('pronunciation', models.FileField(blank=True, null=True, upload_to=functools.partial(core.shortcuts.change_filename_to_temporary, *(), **{'path': 'cards/sounds/'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Pronunciation')),
                ('translit_of_pronunciation', models.TextField(blank=True, null=True, verbose_name='Translit of pronunciation')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='Name')),
                ('picture', models.FileField(upload_to=functools.partial(core.shortcuts.change_filename_to_temporary, *(), **{'path': 'categories/pictures/'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Picture')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='Name')),
                ('picture', models.FileField(upload_to=functools.partial(core.shortcuts.change_filename_to_temporary, *(), **{'path': 'subcategories/pictures/'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Picture')),
                ('categoryId', models.ManyToManyField(to='core.Category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
            options={
                'ordering': ['-data_added'],
            },
        ),
    ]
